#!/usr/bin/env node
'use strict';

/**
 * CloudSSH frontend inliner.
 * Compatible with both:
 * 1) normal Vite output: frontend/dist/index.html + frontend/dist/assets/*
 * 2) single-file Vite output: frontend/dist/index.html only
 *
 * Replace scripts/build-html.js with this file.
 */

const fs = require('node:fs');
const path = require('node:path');

const rootDir = path.resolve(__dirname, '..');
const distDir = path.join(rootDir, 'frontend', 'dist');
const indexPath = path.join(distDir, 'index.html');
const outputPath = path.join(rootDir, 'src', 'worker', 'html.ts');

function fail(message) {
  console.error(`Failed to build and inline frontend: ${message}`);
  process.exit(1);
}

function mimeType(filePath) {
  const ext = path.extname(filePath).toLowerCase();
  return ({
    '.svg': 'image/svg+xml',
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.gif': 'image/gif',
    '.webp': 'image/webp',
    '.ico': 'image/x-icon',
    '.woff': 'font/woff',
    '.woff2': 'font/woff2',
    '.ttf': 'font/ttf',
    '.otf': 'font/otf',
    '.json': 'application/json',
  })[ext] || 'application/octet-stream';
}

function stripQueryAndHash(value) {
  return value.split('#', 1)[0].split('?', 1)[0];
}

function isRemote(value) {
  return /^(?:[a-z]+:)?\/\//i.test(value) || value.startsWith('data:') || value.startsWith('#');
}

function resolveAsset(ref, baseDir = distDir) {
  const clean = decodeURIComponent(stripQueryAndHash(ref));
  if (!clean || isRemote(clean)) return null;
  const relative = clean.startsWith('/') ? clean.slice(1) : clean;
  const candidates = [path.resolve(baseDir, relative), path.resolve(distDir, relative)];
  for (const candidate of candidates) {
    if (candidate.startsWith(distDir) && fs.existsSync(candidate) && fs.statSync(candidate).isFile()) {
      return candidate;
    }
  }
  return null;
}

function toDataUri(filePath) {
  const mime = mimeType(filePath);
  const buf = fs.readFileSync(filePath);
  if (mime === 'image/svg+xml') {
    return `data:${mime};base64,${buf.toString('base64')}`;
  }
  return `data:${mime};base64,${buf.toString('base64')}`;
}

function inlineCssUrls(css, cssDir) {
  return css.replace(/url\(\s*(['"]?)([^'"\)]+)\1\s*\)/g, (full, quote, ref) => {
    const value = ref.trim();
    if (!value || isRemote(value)) return full;
    const filePath = resolveAsset(value, cssDir);
    return filePath ? `url("${toDataUri(filePath)}")` : full;
  });
}

function escapeTemplateLiteral(value) {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

if (!fs.existsSync(indexPath)) {
  fail(`missing ${indexPath}. Vite did not produce frontend/dist/index.html`);
}

console.log('Inlining frontend assets...');
let html = fs.readFileSync(indexPath, 'utf8');

// Inline local stylesheet links. Remote stylesheets are intentionally kept unchanged.
html = html.replace(
  /<link\b([^>]*?)href=["']([^"']+\.css(?:\?[^"']*)?)["']([^>]*)>/gi,
  (tag, before, href) => {
    const cssPath = resolveAsset(href);
    if (!cssPath) return tag;
    const css = inlineCssUrls(fs.readFileSync(cssPath, 'utf8'), path.dirname(cssPath));
    return `<style data-inline-source="${href}">\n${css}\n</style>`;
  },
);

// Inline local module/classic scripts. Remote scripts are intentionally kept unchanged.
html = html.replace(
  /<script\b([^>]*?)src=["']([^"']+\.js(?:\?[^"']*)?)["']([^>]*)><\/script>/gi,
  (tag, before, src, after) => {
    const jsPath = resolveAsset(src);
    if (!jsPath) return tag;
    const js = fs.readFileSync(jsPath, 'utf8').replace(/<\/script/gi, '<\\/script');
    const attrs = `${before} ${after}`.trim();
    const typeMatch = attrs.match(/\btype=["']([^"']+)["']/i);
    const type = typeMatch ? ` type="${typeMatch[1]}"` : '';
    return `<script${type} data-inline-source="${src}">\n${js}\n</script>`;
  },
);

// Inline common local image/icon/font references that appear directly in HTML.
html = html.replace(
  /(\b(?:src|href)=)["']([^"']+)["']/gi,
  (full, prefix, ref) => {
    if (isRemote(ref) || /\.css(?:[?#]|$)|\.js(?:[?#]|$)/i.test(ref)) return full;
    const filePath = resolveAsset(ref);
    if (!filePath) return full;
    const ext = path.extname(filePath).toLowerCase();
    if (!['.svg', '.png', '.jpg', '.jpeg', '.gif', '.webp', '.ico', '.woff', '.woff2', '.ttf', '.otf'].includes(ext)) {
      return full;
    }
    return `${prefix}"${toDataUri(filePath)}"`;
  },
);

// Preserve the export name already used by this fork, if one exists.
let exportName = 'HTML_CONTENT';
if (fs.existsSync(outputPath)) {
  const oldOutput = fs.readFileSync(outputPath, 'utf8');
  const match = oldOutput.match(/export\s+const\s+([A-Za-z_$][\w$]*)\s*=/);
  if (match) exportName = match[1];
}

const generated = `// AUTO-GENERATED by scripts/build-html.js. DO NOT EDIT.\n` +
  `export const ${exportName} = \`${escapeTemplateLiteral(html)}\`;\n`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, generated, 'utf8');

const assetsDir = path.join(distDir, 'assets');
if (!fs.existsSync(assetsDir)) {
  console.log('No frontend/dist/assets directory found; index.html was already self-contained.');
}
console.log(`Frontend inlined successfully: ${path.relative(rootDir, outputPath)}`);
console.log(`Generated size: ${(Buffer.byteLength(generated) / 1024).toFixed(2)} KiB`);
